KP-731 [GCP CLI] Map working directory folder and cwd to run command so it can interact with files on the agent
Kaholo/kaholo-plugin-gcp-cli pull request #3
Opened 2022-06-01 11:33 UTC by xkcm

[**KP-731 in Jira**](https://kaholo.atlassian.net/browse/KP-731)

2022-06-03 09:39 UTC, kenskyfish approved these changes
Works well, very nice.

2022-06-03 10:14 UTC, kenskyfish approved these changes

2022-06-03 13:12 UTC, graddaniel requested changes

2022-06-05 04:42 UTC, kenskyfish approved these changes

2022-06-06 08:40 UTC, graddaniel approved these changes

2022-06-06 08:44 UTC, merged